# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: An Introduction to Taylor's Theorem
author: Se-Jin Kim
copyright: "2025"
logo: ""

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  timeout: 100

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: TaylorSeries.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/soundsflyout/Teaching-Seminar-Taylor-Series # Online location of your book
#  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# This is to enable the proof environment 
sphinx:
  extra_extensions:
    - sphinx_proof
  config:
    proof_minimal_theme: true
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
